### ISSUE TITLE
Question on how to add data

### ISSUE THREAD

**Issue by nFeyz** [Kaseaa/tera-guide#12]
2 questions that i want to ask:

1. How to make it announce/print text for a certain boss skill?
I tried `!guide event text message '{"s-455-200-2204"}' "text here"`
but its not working. Im confused on how to input the argument. (sorry no coding experience here)
even the one in the example `!guide event trigger "h-444-2000-97"`
isnt working for me (invalid values for sub command "event" trigger)

2. How to specify which dg does these code refers too?
or these command only works for the dg that we are in only? 

Thanks

**Comment by Kasea** [comment]
1. the trigger (example trigger) will only work inside harrowhold. You need to be inside the dungeon to activate it, because it needs to load the actual config. as for the other thing, I'm not sure how to explain it to you, since you don't have proper coding experience. Try to look at the example better

2. debug active -> enter dungeon
